# ==========================================
# CONFIGURAÇÃO DO PRODUTOR KAFKA (Aiven - SASL/PLAIN)
# ==========================================
mp.messaging.outgoing.order-created-out.connector=smallrye-kafka
mp.messaging.outgoing.order-created-out.topic=kaffeineshop.orders.created

kafka.bootstrap.servers=${AIVEN_URL_BROKER}

mp.messaging.outgoing.order-created-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.order-created-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# --- CONFIGURAÇÃO DE SEGURANÇA SASL_SSL (Igual ao Python) ---
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=PLAIN
kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="avnadmin" password="${AIVEN_AIVEN_PASSWORD}";

# Validação do certificado do servidor Aiven (equivalente ao ca.pem)
kafka.ssl.endpoint.identification.algorithm=https
# Se você tiver o arquivo ca.pem na pasta certs, pode apontar o truststore padrão do Java ou deixar o truststore do sistema gerenciar:
kafka.ssl.truststore.location=/Users/leynnerroque/Documents/development/projects/kaffeine-shop/src/main/resources/certs/client.truststore.jks
kafka.ssl.truststore.password=${AIVEN_KEY_SET_ONE}
kafka.ssl.truststore.type=JKS


# Configuração do DataSource MySQL (Aiven)
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${AIVEN_USER}
quarkus.datasource.password=${AIVEN_PASSWORD}
quarkus.datasource.jdbc.url=${AIVEN_URL_DB}

# Configuração do Hibernate ORM
quarkus.hibernate-orm.database.generation=none
# (Como usamos Flyway para gerenciar o schema, deixamos o Hibernate apenas validando ou sem gerar DDL automático)

# Configuração do Flyway
quarkus.flyway.migrate-at-start=true

grafana.endpoint=http://localhost:3000
otel-collector.url=http://localhost:4317

quarkus.flyway.baseline-on-migrate=true
quarkus.otel.enabled=false

#Para ambientes locais
#quarkus.http.port=8081