# ==========================================
# CONFIGURAÇÃO DO PRODUTOR KAFKA (Aiven)
# ==========================================
# Canal de mensageria
mp.messaging.outgoing.order-created-out.connector=smallrye-kafka
mp.messaging.outgoing.order-created-out.topic=kaffeineshop.orders.created

# Host do Kafka no Aiven
kafka.bootstrap.servers=${AIVEN_URL_BROKER}

# Serializadores
mp.messaging.outgoing.order-created-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.order-created-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# --- CONFIGURAÇÃO DE SEGURANÇA SSL (Aiven) ---
mp.messaging.outgoing.order-created-out.ssl.endpoint.identification.algorithm=
kafka.kafka.security.protocol=SSL

# Truststore (Valida o certificado do servidor Aiven)
kafka.kafka.ssl.truststore.location=/Users/leynnerroque/Documents/development/projects/kaffeine-shop/src/main/resources/certs/client.truststore.jks
kafka.kafka.ssl.truststore.password=${AIVEN_KEY_SET_ONE}
kafka.kafka.ssl.truststore.type=JKS

# Keystore (Autentica a sua aplicação perante o Aiven)
kafka.kafka.ssl.keystore.location=/Users/leynnerroque/Documents/development/projects/kaffeine-shop/src/main/resources/certs/client.p12
kafka.kafka.ssl.keystore.password=${AIVEN_KEY_SET_TWO}
kafka.kafka.ssl.keystore.type=PKCS12


# Configuração do DataSource MySQL (Aiven)
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${AIVEN_USER}
quarkus.datasource.password=${AIVEN_PASSWORD}
quarkus.datasource.jdbc.url=${AIVEN_URL_DB}

# Configuração do Hibernate ORM
quarkus.hibernate-orm.database.generation=none
# (Como usamos Flyway para gerenciar o schema, deixamos o Hibernate apenas validando ou sem gerar DDL automático)

# Configuração do Flyway
quarkus.flyway.migrate-at-start=true

grafana.endpoint=http://localhost:3000
otel-collector.url=http://localhost:4317

quarkus.flyway.baseline-on-migrate=true
quarkus.otel.enabled=false